/*
 * Copyright (c) 2015 waynejo
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
 * the Software, and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
 * FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
 * COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
 * IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_waynejo_androidndkgif_GifDecoder */

#ifndef _Included_com_waynejo_androidndkgif_GifDecoder
#define _Included_com_waynejo_androidndkgif_GifDecoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_waynejo_androidndkgif_GifDecoder
 * Method:    nativeInit
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_waynejo_androidndkgif_GifDecoder_nativeInit
  (JNIEnv *, jobject);

/*
 * Class:     com_waynejo_androidndkgif_GifDecoder
 * Method:    nativeClose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_waynejo_androidndkgif_GifDecoder_nativeClose
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_waynejo_androidndkgif_GifDecoder
 * Method:    nativeLoad
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_waynejo_androidndkgif_GifDecoder_nativeLoad
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_waynejo_androidndkgif_GifDecoder
 * Method:    nativeGetFrameCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_waynejo_androidndkgif_GifDecoder_nativeGetFrameCount
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_waynejo_androidndkgif_GifDecoder
 * Method:    nativeGetFrame
 * Signature: (JI)Landroid/graphics/Bitmap;
 */
JNIEXPORT jobject JNICALL Java_com_waynejo_androidndkgif_GifDecoder_nativeGetFrame
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_waynejo_androidndkgif_GifDecoder
 * Method:    nativeGetDelay
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_waynejo_androidndkgif_GifDecoder_nativeGetDelay
        (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_waynejo_androidndkgif_GifDecoder
 * Method:    nativeGetWidth
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_waynejo_androidndkgif_GifDecoder_nativeGetWidth
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_waynejo_androidndkgif_GifDecoder
 * Method:    nativeGetHeight
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_waynejo_androidndkgif_GifDecoder_nativeGetHeight
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
