/*
 * Copyright (c) 2015 waynejo
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
 * the Software, and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
 * FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
 * COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
 * IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_waynejo_androidndkgif_GifEncoder */

#ifndef _Included_com_waynejo_androidndkgif_GifEncoder
#define _Included_com_waynejo_androidndkgif_GifEncoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_waynejo_androidndkgif_GifEncoder
 * Method:    nativeInit
 * Signature: (IILjava/lang/String;II)J
 */
JNIEXPORT jlong JNICALL Java_com_waynejo_androidndkgif_GifEncoder_nativeInit
  (JNIEnv *, jobject, jint, jint, jstring, jint, jint);

/*
 * Class:     com_waynejo_androidndkgif_GifEncoder
 * Method:    nativeClose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_waynejo_androidndkgif_GifEncoder_nativeClose
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_waynejo_androidndkgif_GifEncoder
 * Method:    nativeSetDither
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_waynejo_androidndkgif_GifEncoder_nativeSetDither
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     com_waynejo_androidndkgif_GifEncoder
 * Method:    nativeSetThreadCount
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_waynejo_androidndkgif_GifEncoder_nativeSetThreadCount
        (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_waynejo_androidndkgif_GifEncoder
 * Method:    nativeEncodeFrame
 * Signature: (JLandroid/graphics/Bitmap;I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_waynejo_androidndkgif_GifEncoder_nativeEncodeFrame
  (JNIEnv *, jobject, jlong, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
