
// Objective-C API for talking to the following Go packages
//
//	weiss
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Weiss_FRAMEWORK_H__
#define __Weiss_FRAMEWORK_H__

#include "Weiss.objc.h"
#include "Universe.objc.h"

#endif
