// Objective-C API for talking to weiss Go package.
//   gobind -lang=objc weiss
//
// File is generated by gobind. Do not edit.

#ifndef __Weiss_H__
#define __Weiss_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class WeissAnswer;
@class WeissOneZeroReq;
@class WeissOneZeroRes;
@class WeissQuestion;

@interface WeissAnswer : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) long type;
@property (nonatomic) long ttl;
@property (nonatomic) NSString* _Nonnull data;
@end

@interface WeissOneZeroReq : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped method OneZeroReq.PrePare with unsupported parameter or return types

@end

@interface WeissOneZeroRes : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) long status;
@property (nonatomic) BOOL tc;
@property (nonatomic) BOOL rd;
@property (nonatomic) BOOL ra;
@property (nonatomic) BOOL ad;
@property (nonatomic) BOOL cd;
// skipped field OneZeroRes.Question with unsupported type: []weiss.Question

// skipped field OneZeroRes.Answer with unsupported type: []weiss.Answer

@end

@interface WeissQuestion : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull name;
@property (nonatomic) long type;
@end

@interface Weiss : NSObject
// skipped variable OneZeroCache with unsupported type: struct{Data map[string]string; Lock sync.RWMutex}

+ (NSString* _Nonnull) pixiV_API_IP;
+ (void) setPIXIV_API_IP:(NSString* _Nonnull)v;

@end

FOUNDATION_EXPORT void WeissClose(void);

FOUNDATION_EXPORT void WeissStart(NSString* _Nullable port, NSString* _Nullable jsonData);

#endif
