name: Build Android APK

on:
  push:
    branches: master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.44.6'

      - name: Flutter version
        run: flutter --version

      - name: Get app dependencies
        run: flutter pub get

      - name: Get rhttp dependencies
        working-directory: plugins/rhttp/rhttp
        run: flutter pub get

      - name: Generate rhttp freezed files
        working-directory: plugins/rhttp/rhttp
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Generate app files
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Build Release APKs
        run: flutter build apk --release --split-per-abi --tree-shake-icons

      - uses: actions/upload-artifact@v4
        with:
          name: release-apks
          path: build/app/outputs/flutter-apk/*.apk