name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions/setup-java@v1.4.3
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1.4.0
      with:
        flutter-version: '1.27.0-4.0.pre'
        channel: 'dev'
    - run: flutter pub get
    - run: flutter pub run intl_utils:generate
    - run: flutter pub run build_runner build
    - run: flutter build apk --no-sound-null-safety